### ISSUE TITLE
0.1.0 Release Overview

### ISSUE THREAD

**Issue by sigrunixia** [Obsidian-TTRPG-Community/13th-Age-SRD-Markdown#1]
**Conversion Project:** 13th Age

**Watch Link**: [Pelgrane Press](https://pelgranepress.com/2013/10/24/the-archmage-engine-13th-age-srd/)

## To-Do Complete
- [X] Legal
- [x] Icons
- [x] Character-Rules
	- [X] Character-Rules.md (MOC Page) 	
	- [X] Gear
		- [x] Armor-Categories.md
		- [x] Economy.md
		- [X] Equipment-Price.Guide.md
		- [x] Melee-Weapon-Categories.md
		- [x] Ranged-Weapon-Categories.md
	- [X] Feats
		- [X] Feats-Per-Level.md
		- [X] General-Feats.md
		- [X] Feats Folder
	- [X] Abilities.md
	- [X] Background-and-Skill-Checks.md
- [X] Races
- [x] Classes
- [x] Multiclassing
- [x] #16
- [x] Running-The-Game
- [x] Monsters #11 
	- [x] Monster Creation
	- [x] Monster Rules
	- [x] Monster Key
	- [x] Monster List
	- [x] Underkraken
- [x] Magic-Items
	- [x] Artifacts
	- [x] Chakras
	- [x] Magic Item Basics
	- [x] Magic Item Descriptions
	- [x] One Use Items
	- [x] True Magic Items

#### Content
- [x] Check that changes between 3.0 and 4.0 are reflected
#### Formatting
- [x] Check that all Tables have `^13A-` block links.
- [x] Recheck that changes between 3.0 and 4.0 are reflected

#### 3rd Plugin Support
- [X] Folder Notes
- [X] Finish integrating support for Dice Roller
- [X] Confirm Monsters fully integrated for Initiative Tracker
- [x] Create Fantasy Statblocks for Every Monster

**Comment by sigrunixia** [comment]
Closing as this is pretty much complete.
